language: python

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov

env:
  - CODECOV_TOKEN='7ff9a7f8-e542-4aca-8b72-53347cd6b317'

services:
  - docker

before_install:
  - docker build .

install:
  - pip install codecov

script:
  - coverage run wololo.py
  - coverage run another.py